version: "0.1"
services:
  rserver:
    build: .
    expose:
      - 8000
    volumes:
      - ./server:/server
  nginx:
    image: "nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf