version: "0.1"
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./server:/server
  proxy:
    image: "nginx"
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf